language: python
sudo: false
cache:
  directories:
  - "${HOME}/bin"
env:
  global:
  - PATH="${HOME}/bin
  - TMPDIR="${TMPDIR:-/tmp}"
  - VERSION="0.11.7"
before_install:
  - if ! terraform version ; then
      mkdir -p "${HOME}/bin"
      pushd "${TMPDIR}" ;
      curl -sSL
        -o terraform.zip
        "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip" ;
      unzip terraform.zip ;
      mv -v terraform "${HOME}/bin/terraform" ;
      chmod +x "${HOME}/bin/terraform" ;
      popd ;
      terraform version ;
    fi
script:
  - test/check-tf.sh
